#pragma once

#include <string_view>

namespace masters::detail {

// Quotient by the vector space spanned by symmetry differences, not the ideal
// generated by those differences. Keep the original candidate preference.
inline constexpr std::string_view kIsolatedSymmetryBasisProcedure = R"SINGULAR(
proc fr_select_symmetry_basis(ideal candidates, ideal relations, ideal KB, ideal GX)
{
  int n=size(KB);
  matrix coordinates[n][n];
  int current_rank=0; int relation_rank=0; int selected_count=0;
  ideal selected; ideal stream;
  int phase,i,j,found,next_rank; intvec exponent;
  poly nf;
  for (phase=0; phase<2; phase++)
  {
    if (phase==0) { stream=relations; }
    else { stream=candidates; }
    for (i=1; i<=size(stream); i++)
    {
      if (current_rank==n) { break; }
      for (j=1; j<=n; j++) { coordinates[j,current_rank+1]=0; }
      nf=reduce(stream[i],GX);
      while (nf!=0)
      {
        exponent=leadexp(nf); found=0;
        for (j=1; j<=n; j++)
        {
          if (exponent==leadexp(KB[j]))
          {
            coordinates[j,current_rank+1]=leadcoef(nf);
            found=1; break;
          }
        }
        if (found==0) { return(list(selected,1)); }
        nf=nf-lead(nf);
      }
      next_rank=rank(coordinates);
      if (next_rank>current_rank)
      {
        current_rank=next_rank;
        if (phase==1)
        {
          selected_count++;
          selected[selected_count]=stream[i];
        }
      }
    }
    if (phase==0) { relation_rank=current_rank; }
  }
  if (current_rank!=n || selected_count!=n-relation_rank)
  { return(list(selected,2)); }
  return(list(selected,0));
}
)SINGULAR";

} // namespace masters::detail
